import type { AsanaConfig, TranslationJob } from "@prisma/client"

const ASANA_API = "https://app.asana.com/api/1.0"

interface AsanaTask {
  gid: string
  name: string
  permalink_url: string
}

function getHeaders(token: string) {
  return {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
    Accept: "application/json",
  }
}

export async function createTranslationTask(
  config: AsanaConfig,
  job: TranslationJob & { client: { name: string } }
): Promise<AsanaTask> {
  const customFields: Record<string, string | number> = {}
  if (config.sourceLangFieldGid) customFields[config.sourceLangFieldGid] = job.sourceLang
  if (config.targetLangFieldGid) customFields[config.targetLangFieldGid] = job.targetLang
  if (config.confidenceFieldGid && job.confidenceScore !== null) {
    customFields[config.confidenceFieldGid] = Math.round((job.confidenceScore ?? 0) * 100)
  }
  if (config.contentTypeFieldGid) customFields[config.contentTypeFieldGid] = job.contentType

  const taskName = `[Translation] ${job.client.name} · ${job.sourceLang} → ${job.targetLang} · ${new Date().toLocaleDateString("en-GB")}`

  const notes = buildTaskDescription(job)

  const body = {
    data: {
      name: taskName,
      projects: [config.projectGid],
      notes,
      custom_fields: customFields,
    },
  }

  const res = await fetch(`${ASANA_API}/tasks`, {
    method: "POST",
    headers: getHeaders(config.accessToken),
    body: JSON.stringify(body),
  })

  if (!res.ok) {
    const error = await res.text()
    throw new Error(`Asana task creation failed: ${res.status} ${error}`)
  }

  const { data } = (await res.json()) as { data: AsanaTask }
  return data
}

function buildTaskDescription(job: TranslationJob): string {
  const confidence = job.confidenceScore !== null
    ? `${Math.round((job.confidenceScore ?? 0) * 100)}%`
    : "Pending"

  return `## Translation Review

**Source language:** ${job.sourceLang}
**Target language:** ${job.targetLang}
**Content type:** ${job.contentType}
**AI confidence score:** ${confidence}

---

### Source Copy
${job.sourceText}

---

### Translated Copy
${job.translatedText ?? ""}

---

### Reviewer Notes
${job.reviewerNotes ?? "No specific notes."}

---
*Generated by Lingua AI Translation Engine*`
}

export async function registerWebhook(
  config: AsanaConfig,
  webhookTarget: string
): Promise<string> {
  const body = {
    data: {
      resource: config.projectGid,
      target: webhookTarget,
      filters: [
        { resource_type: "story", action: "added" },
        { resource_type: "task", action: "changed", fields: ["notes"] },
      ],
    },
  }

  const res = await fetch(`${ASANA_API}/webhooks`, {
    method: "POST",
    headers: getHeaders(config.accessToken),
    body: JSON.stringify(body),
  })

  if (!res.ok) {
    const error = await res.text()
    throw new Error(`Asana webhook registration failed: ${res.status} ${error}`)
  }

  const { data } = (await res.json()) as { data: { gid: string } }
  return data.gid
}
